---

# Inisghts and analytics-api Deployment:

- name: Bootstrap instances
  hosts: all
  gather_facts: no
  become: true
  roles:
    - python

- name: Configure analytics servers
  hosts: analytics_servers
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      when: SWAPFILE_SIZE is defined and SWAPFILE_SIZE != ""
    - role: nginx
      nginx_sites:
        - insights
#        - analytics_api
      nginx_default_sites:
        - insights
    - insights
    - analytics_api
